# Generated by Django 4.2.30 on 2026-08-22 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked')], default='available', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, help_text="When the hold auto-expires. Must be NULL unless status='held'.", null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venues.seatcategory')),
                ('holder', models.ForeignKey(blank=True, help_text='The user currently holding this seat (null if available or booked).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seats', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='venues.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_seats', to='events.show')),
            ],
            options={
                'db_table': 'show_seats',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.show')),
                ('show_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.showseat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['status', 'hold_expires_at'], name='idx_showseat_status_expiry'),
        ),
        migrations.AddIndex(
            model_name='showseat',
            index=models.Index(fields=['show', 'status'], name='idx_showseat_show_status'),
        ),
        migrations.AddConstraint(
            model_name='showseat',
            constraint=models.CheckConstraint(check=models.Q(('status', 'held'), ('hold_expires_at__isnull', True), _connector='OR'), name='hold_expires_at_only_when_held'),
        ),
        migrations.AlterUniqueTogether(
            name='showseat',
            unique_together={('show', 'seat')},
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('show_seat',), name='unique_active_booking_per_show_seat'),
        ),
    ]
