# Generated by Django 4.2.30 on 2026-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_delivery_failed',
            field=models.BooleanField(default=False),
        ),
    ]
