# Generated by Django 4.2.30 on 2026-08-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_email_delivery_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='showseat',
            name='is_waitlist_offer',
            field=models.BooleanField(default=False, help_text='True if this seat is currently held as a waitlist offer. Ignored by generic release_expired_holds task.'),
        ),
    ]
