# Generated by Django 4.2.30 on 2026-08-22 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'seat categories',
                'db_table': 'seat_categories',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('total_capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'venues',
            },
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Main Hall', 'Balcony'", max_length=100)),
                ('total_rows', models.PositiveIntegerField()),
                ('total_columns', models.PositiveIntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='venues.venue')),
            ],
            options={
                'db_table': 'seat_layouts',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_name', models.CharField(help_text="e.g. 'A', 'B', 'AA'", max_length=10)),
                ('col_number', models.PositiveIntegerField()),
                ('coord_x', models.FloatField(help_text='X-coordinate for seat-map rendering')),
                ('coord_y', models.FloatField(help_text='Y-coordinate for seat-map rendering')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='venues.seatcategory')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.seatlayout')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.venue')),
            ],
            options={
                'db_table': 'seats',
                'unique_together': {('venue', 'row_name', 'col_number')},
            },
        ),
    ]
