# Generated by Django 4.2.30 on 2026-08-22 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.seatcategory')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='events.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'db_table': 'waitlist_entries',
                'indexes': [models.Index(fields=['show', 'category', 'status', 'created_at'], name='idx_waitlist_lookup')],
            },
        ),
        migrations.AddConstraint(
            model_name='waitlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('show', 'user', 'category'), name='unique_active_waitlist_per_user_show_category'),
        ),
    ]
