# Generated by Django 4.2.30 on 2026-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, help_text="When the offer to book this seat expires. Must be NULL unless status='offered'.", null=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('offered', 'Offered'), ('expired', 'Expired')], default='waiting', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='waitlistentry',
            constraint=models.CheckConstraint(check=models.Q(('status', 'offered'), ('offer_expires_at__isnull', True), _connector='OR'), name='offer_expires_at_only_when_offered'),
        ),
    ]
